--- 
- hosts: ansible-sample
  tasks:
   - name: check if shellmodule-ana already exists
     stat:
     path: "~/shellmodule-ana"
     register: shellmodulevariable

   - debug: var=shellmodulevariable

   - name: create folder using shell module
     shell: "mkdir ~/shellmodule-ana"
     when: shellmodulevariable.stat.exist !=true

   - name: create folder using file module
     file:
     state: directory
     path: "~/filemodule-ana"
